language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
- openjdk8
- openjdk11
env: BUILD_TOOL=gradlew
install: ./gradlew --console=plain assemble
script: ./gradlew --console=plain check
jobs:
  include:
  - name: Gradle (Java 8)
    jdk: openjdk8
    env: BUILD_TOOL=gradle
    install: gradle --console=plain assemble
    script:  gradle --console=plain check
  - name: Gradle (Java 11)
    jdk: openjdk11
    env: BUILD_TOOL=gradle
    install: gradle --console=plain assemble
    script:  gradle --console=plain check
  - name: Maven (Java 8)
    jdk: openjdk8
    env: BUILD_TOOL=mvn
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
  - name: Maven (Java 11)
    jdk: openjdk11
    env: BUILD_TOOL=mvn
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
