language: java
jdk:
- openjdk8
- openjdk11
env:
- BUILD_TOOL=gradle
- BUILD_TOOL=gradlew
- BUILD_TOOL=mvn
install: 
- [ $BUILD_TOOL == gradle ] && gradle assemble
- [ $BUILD_TOOL == gradlew ] && ./gradlew assemble
- [ $BULD_TOOL == mvn ] && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- [ $BUILD_TOOL == gradle ] && gradle check
- [ $BUILD_TOOL == gradlew ] && ./gradlew check
- [ $BULD_TOOL == mvn ] && mvn test -B