language: java
jdk:
- openjdk8
- openjdk11
env:
- BUILD_TOOL=gradle
- BUILD_TOOL=gradlew
- BUILD_TOOL=mvn
install: skip
script: skip
jobs:
  include:
  - name: Gradle
    env: BUILD_TOOL=gradle
    install: gradle assemble
    script:  gradle check
  - name: Gradle Wrapper
    env: BUILD_TOOL=gradlew
    install: ./gradlew assemble
    script: ./gradlew check
  - name: Maven
    env: BUILD_TOOL=mvn
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
