language: java
jdk: 
- openjdk8
- openjdk11
jobs:
  include:
  - name: Gradle
    install: gradle assemble
    script:  gradle check
  - name: Maven
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
