language: java
jdk:
- openjdk8
- openjdk11
jobs:
  include:
  - name: Gradle (Java 8)
    jdk: openjdk8
    env: BUILD_TOOL=gradle
    install: gradle assemble
    script:  gradle check
  - name: Gradle (Java 11)
    jdk: openjdk11
    env: BUILD_TOOL=gradle
    install: gradle assemble
    script:  gradle check
  - name: Maven (Java 8)
    jdk: openjdk8
    env: BUILD_TOOL=mvn
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
  - name: Maven (Java 11)
    jdk: openjdk11
    env: BUILD_TOOL=mvn
    install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:  mvn test -B
